name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 885626464789.dkr.ecr.us-east-1.amazonaws.com/clo835-week3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Build the Docker image
        run: docker build -t clo835-week3 .

      - name: Tag the Docker image
        run: docker tag clo835-week3:latest 885626464789.dkr.ecr.us-east-1.amazonaws.com/clo835-week3:latest

      - name: Push the Docker image to Amazon ECR
        run: docker push 885626464789.dkr.ecr.us-east-1.amazonaws.com/clo835-week3:latest
